config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :topics do
  resources :posts, except: [:index] do
    resources :summaries, only: [:new, :create, :show]
  end
end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/summary.rb
# == Schema Information
#
# Table name: summaries
#
#  id          :integer          not null, primary key
#  post_id     :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Summary < ActiveRecord::Base
  belongs_to :post
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:post_id])
    @summary = Summary.new
    authorize @summary
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:post_id])
    @summary = @post.build_summary(params.require(:summary).permit(:description))

    authorize @summary
    if @summary.save
      flash[:notice] = "Your post summary was saved"
      redirect_to [@topic, @post]
    else
      flash[:error] = "Sorry. There was an error saving your summary. Please try again"
      render :new
    end
  end

  def show
    @summary = Summary.find(params[:id])
    @post = Post.find(params[:post_id])
    @topic = Topic.find(params[:topic_id])
    authorize @summary
  end
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/summary/new.html.erb
<h1>summary#new<h1>
<%= form_for @summary, url: post_summary_path do |f| %>
   <%= f.label :description %>
   <%= f.text_area :description %>
   <%= f.submit "Save" %>
<% end %>

app/views/summary/show.html.erb
<h1>Summary#show</h1>
<p><%= @summary.description %></p>
<% if @summary %>
  <p><%= @summary.description %></p>
<% else %>
  <p>No Summary </p>
<% end %>
 <%= debug @summary %>