config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :topics do
  resources :posts, except: [:index] do
    resources :summaries, only: [:new, :create, :show]
  end
end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  topic_id   :integer
#

class Post < ActiveRecord::Base
  has_many :comments
  has_one :summary
  belongs_to :user
  belongs_to :topic

  default_scope { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    current_user.posts << @post
    autorize@post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
    authorize @topic
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
    if @post.save
       @post.create_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:notice] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <% if post.image? %>
    <div class="form-group">
      <p>Current Post Image</p>
      <%= image_tag( post.image.url(:medium) ) %>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group">
      <%= f.submit "Update", class: 'btn btn-success' %>
    </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to (markdown_to_html post.title), [post.topic, post] %>
     <small>
       <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
       submitted <%= time_ago_in_words(post.created_at) %> ago by
       <%= post.user.name %><br>
       <%= post.comments.count %> Comments
      </small>
    </h4>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Popular</h1>
    <p class="lead">Active posts this week</p>
    <%= render @posts %>
    <%= will_paginate @posts %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
    <% if @post.summary %>
      <%=  @post.summary.description %>
    <% else %>
      <%= link_to "Create Summary", new_topic_post_summary_path(@topic, @post), class: 'btn btn-success'%>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>